
import React, { useState } from 'react';
import { generateImage } from '../lib/gemini';

const aspectRatios = [
  { label: '1:1', value: '1:1' },
  { label: '3:4', value: '3:4' },
  { label: '4:3', value: '4:3' },
  { label: '9:16', value: '9:16' },
  { label: '16:9', value: '16:9' },
];

const ImageGeneratorPanel: React.FC = () => {
  const [prompt, setPrompt] = useState<string>('');
  const [selectedAspectRatio, setSelectedAspectRatio] = useState<string>('1:1');
  const [generatedImageUrl, setGeneratedImageUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerateImage = async () => {
    if (!prompt.trim()) {
      setError('Please enter a prompt.');
      return;
    }

    setIsLoading(true);
    setError(null);
    setGeneratedImageUrl(null);

    try {
      const imageUrl = await generateImage(
        prompt,
        selectedAspectRatio as '1:1' | '3:4' | '4:3' | '9:16' | '16:9',
      );
      if (imageUrl) {
        setGeneratedImageUrl(imageUrl);
      } else {
        setError('Image generation failed. Please try a different prompt.');
      }
    } catch (err: any) {
      setError(`Error: ${err.message || 'Unknown error'}.`);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col flex-1 p-6 bg-transparent overflow-y-auto custom-scrollbar">
      <h2 className="text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400 mb-6">Image Creator</h2>
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 flex-1">
        {/* Controls Panel */}
        <div className="glass-panel rounded-xl shadow-xl p-6 flex flex-col space-y-6">
          <div>
            <label htmlFor="image-prompt" className="block text-slate-300 text-sm font-medium mb-2">Prompt</label>
            <textarea
              id="image-prompt"
              className="w-full p-3 rounded-md bg-slate-900/50 text-slate-100 border border-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-500 resize-y"
              rows={6}
              placeholder="A futuristic synth studio with neon lights..."
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              disabled={isLoading}
            ></textarea>
          </div>
          <div>
            <label htmlFor="aspect-ratio" className="block text-slate-300 text-sm font-medium mb-2">Aspect Ratio</label>
            <div className="grid grid-cols-5 gap-2">
              {aspectRatios.map((ratio) => (
                <button
                  key={ratio.value}
                  className={`py-2 rounded-md text-sm font-medium transition-colors duration-200 ${selectedAspectRatio === ratio.value ? 'bg-cyan-600 text-white shadow-cyan-glow' : 'bg-slate-700/50 text-slate-300 hover:bg-slate-700'}`}
                  onClick={() => setSelectedAspectRatio(ratio.value)}
                  disabled={isLoading}
                >
                  {ratio.label}
                </button>
              ))}
            </div>
          </div>
          <div className="flex-grow"></div>
          <button
            className="w-full py-3 px-6 rounded-md bg-gradient-to-r from-cyan-500 to-blue-500 text-white font-bold text-lg hover:from-cyan-600 hover:to-blue-600 transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-cyan-500 disabled:opacity-50 disabled:cursor-not-allowed"
            onClick={handleGenerateImage}
            disabled={isLoading || !prompt.trim()}
          >
            {isLoading ? 'Generating...' : 'Generate Image'}
          </button>
        </div>

        {/* Display Panel */}
        <div className="glass-panel rounded-xl shadow-xl p-6 flex items-center justify-center min-h-[300px]">
          {isLoading && <div className="text-slate-400">Creating your vision...</div>}
          {error && <div className="text-red-400 text-center">{error}</div>}
          {!isLoading && !error && !generatedImageUrl && (
            <div className="text-center text-slate-500">
              <svg className="w-16 h-16 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg>
              <p>Your generated image will appear here.</p>
            </div>
          )}
          {generatedImageUrl && (
            <div className="relative group">
              <img src={generatedImageUrl} alt="Generated by AI" className="max-w-full max-h-[60vh] h-auto rounded-lg shadow-2xl" />
              <a href={generatedImageUrl} download="ai-generated-image.jpg" className="absolute bottom-3 right-3 bg-slate-900/70 text-white text-xs px-3 py-1 rounded-md opacity-0 group-hover:opacity-100 transition-opacity">
                Download
              </a>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ImageGeneratorPanel;
